"""empty message

Revision ID: 76c8fb4f40d
Revises: None
Create Date: 2015-10-14 03:58:20.047016

"""

# revision identifiers, used by Alembic.
revision = '76c8fb4f40d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_tbl', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_tbl', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
